### ISSUE TITLE
复制图片地址控制台+报错

### ISSUE THREAD

**Issue by jonntd** [XPoet/picx#314]
vendor.9cd0ebcb.js:13 TypeError: Cannot destructure property 'rule' of 'a.imageLinkType.presetList[i]' as it is undefined.
    at sa (index.69025434.js:1:34526)
    at ra (index.69025434.js:1:35198)
    at e.imgObj.uploadStatus.progress.n.onClick.a.<computed>.a.<computed> (index.69025434.js:1:65117)
    at dn (vendor.9cd0ebcb.js:13:13345)
    at pn (vendor.9cd0ebcb.js:13:13415)
    at HTMLDivElement.n (vendor.9cd0ebcb.js:15:47791)
（匿名） @ vendor.9cd0ebcb.js:13
hn @ vendor.9cd0ebcb.js:13
dn @ vendor.9cd0ebcb.js:13
pn @ vendor.9cd0ebcb.js:13
n @ vendor.9cd0ebcb.js:15

**Comment by XPoet** [comment]
1、请在 https://picx.xpoet.cn/ 中使用，确保你使用的 PicX 是最新版本。
2、请清除一下浏览器缓存，或退出重新登录后使用。
3、请确保你的浏览器是否允许剪贴板复制功能。
