### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by JakeWoki** [XPoet/picx#66]
```node
npm i
npm run dev
```
```node
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  virtual:pwa-register (imported by C:/Users/12976/vue/picx/src/common/utils/registerSW.ts)

Are they installed?
    at optimizeDeps (C:\Users\12976\vue\picx\node_modules\vite\dist\node\chunks\dep-972722fa.js:73454:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOptimize (C:\Users\12976\vue\picx\node_modules\vite\dist\node\chunks\dep-972722fa.js:74167:48)
    at async Server.httpServer.listen (C:\Users\12976\vue\picx\node_modules\vite\dist\node\chunks\dep-972722fa.js:74183:21)
```
`npm run serve`打开`http://localhost:5000/`后报`Cannot GET /`

**Comment by JakeWoki** [comment]
另外用github做图床会被封外链吗？之前查到Gitee外链会被封的

**Comment by XPoet** [comment]
没必要额外部署，直接使用 picx.xpoet.cn 即可，作者会一直更新维护。GitHub 不太可能封外链，放心使用。

**Comment by jonsam-ng** [comment]
How is this problem solved? I tried running the project and it still reports an error.
